/**
 * https://soynopvqvkjpezo.form.io/yabei
 * formio 生成的表单json
 */

export const json = {
    "_id":"5c7246202039e025fc99b4dc",
    "type":"form",
    "tags":[

    ],
    "owner":"5c63ac25643ccc6dc0af2611",
    "components":[
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "label":"Select Boxes",
            "key":"selectBoxes2",
            "values":[
                {
                    "value":"",
                    "label":"",
                    "shortcut":""
                }
            ],
            "inline":false,
            "protected":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "validate":{
                "required":false
            },
            "type":"selectboxes",
            "labelPosition":"top",
            "optionsLabelPosition":"right",
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            },
            "tooltip":"entwr \nsdigh\nskdjgkg"
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "label":"Date Time",
            "key":"dateTime2",
            "placeholder":"",
            "format":"yyyy-MM-dd a",
            "enableDate":true,
            "enableTime":true,
            "defaultDate":"",
            "datepickerMode":"day",
            "datePicker":{
                "showWeeks":true,
                "startingDay":0,
                "initDate":"",
                "minMode":"day",
                "maxMode":"year",
                "yearRows":4,
                "yearColumns":5,
                "minDate":null,
                "maxDate":null,
                "datepickerMode":"day"
            },
            "timePicker":{
                "hourStep":1,
                "minuteStep":1,
                "showMeridian":true,
                "readonlyInput":false,
                "mousewheel":true,
                "arrowkeys":true
            },
            "protected":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "validate":{
                "required":false,
                "custom":""
            },
            "type":"datetime",
            "labelPosition":"top",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            }
        },
        {
            "key":"content2",
            "label":"Content",
            "input":false,
            "tag":"p",
            "attrs":[
                {
                    "value":"",
                    "attr":""
                }
            ],
            "className":"",
            "content":"<div>Application </div>\n<div></div>",
            "type":"htmlelement",
            "hideLabel":true,
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            }
        },
        {
            "autofocus":false,
            "input":true,
            "inputType":"checkbox",
            "tableView":true,
            "label":"checkboxField",
            "dataGridLabel":false,
            "key":"checkboxField",
            "defaultValue":false,
            "protected":false,
            "persistent":true,
            "hidden":false,
            "name":"",
            "value":"",
            "clearOnHide":true,
            "validate":{
                "required":false
            },
            "type":"checkbox",
            "labelPosition":"right",
            "hideLabel":true,
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            }
        },
        {
            "clearOnHide":false,
            "key":"fieldset",
            "input":false,
            "tableView":false,
            "legend":"",
            "components":[
                {
                    "autofocus":false,
                    "input":true,
                    "tableView":true,
                    "label":"Select",
                    "key":"fieldsetSelect",
                    "placeholder":"",
                    "data":{
                        "values":[
                            {
                                "value":"",
                                "label":""
                            }
                        ],
                        "json":"",
                        "url":"",
                        "resource":"",
                        "custom":""
                    },
                    "dataSrc":"values",
                    "valueProperty":"",
                    "defaultValue":"",
                    "refreshOn":"",
                    "filter":"",
                    "authenticate":false,
                    "template":"<span>{{ item.label }}</span>",
                    "multiple":false,
                    "protected":false,
                    "unique":false,
                    "persistent":true,
                    "hidden":false,
                    "clearOnHide":true,
                    "validate":{
                        "required":false
                    },
                    "type":"select",
                    "labelPosition":"top",
                    "tags":[

                    ],
                    "conditional":{
                        "show":"",
                        "when":null,
                        "eq":""
                    },
                    "properties":{

                    }
                },
                {
                    "autofocus":false,
                    "input":true,
                    "tableView":true,
                    "label":"Select",
                    "key":"fieldsetSelect2",
                    "placeholder":"",
                    "data":{
                        "values":[
                            {
                                "value":"",
                                "label":""
                            }
                        ],
                        "json":"",
                        "url":"",
                        "resource":"",
                        "custom":""
                    },
                    "dataSrc":"values",
                    "valueProperty":"",
                    "defaultValue":"",
                    "refreshOn":"",
                    "filter":"",
                    "authenticate":false,
                    "template":"<span>{{ item.label }}</span>",
                    "multiple":false,
                    "protected":false,
                    "unique":false,
                    "persistent":true,
                    "hidden":false,
                    "clearOnHide":true,
                    "validate":{
                        "required":false
                    },
                    "type":"select",
                    "labelPosition":"top",
                    "tags":[

                    ],
                    "conditional":{
                        "show":"",
                        "when":null,
                        "eq":""
                    },
                    "properties":{

                    }
                }
            ],
            "type":"fieldset",
            "hideLabel":true,
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            }
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "label":"Resource",
            "key":"resource",
            "placeholder":"",
            "resource":"5c65256c3666602188919dd5",
            "project":"soynopvqvkjpezo",
            "defaultValue":"",
            "template":"<span>{{ item.data }}</span>",
            "selectFields":"214324",
            "searchFields":"",
            "multiple":false,
            "protected":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "validate":{
                "required":false
            },
            "defaultPermission":"",
            "type":"resource",
            "labelPosition":"top",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            },
            "tabindex":"we"
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "label":"Date Time",
            "key":"dateTime3",
            "placeholder":"",
            "format":"dd-MMM-yyyy",
            "enableDate":true,
            "enableTime":false,
            "defaultDate":"",
            "datepickerMode":"day",
            "datePicker":{
                "showWeeks":true,
                "startingDay":0,
                "initDate":"",
                "minMode":"day",
                "maxMode":"year",
                "yearRows":4,
                "yearColumns":5,
                "minDate":null,
                "maxDate":"2008-02-13T16:00:00.000Z",
                "datepickerMode":"day"
            },
            "timePicker":{
                "hourStep":1,
                "minuteStep":1,
                "showMeridian":false,
                "readonlyInput":false,
                "mousewheel":true,
                "arrowkeys":true
            },
            "protected":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "validate":{
                "required":false,
                "custom":""
            },
            "type":"datetime",
            "labelPosition":"top",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            }
        },
        {
            "clearOnHide":false,
            "input":false,
            "key":"table",
            "numRows":1,
            "numCols":2,
            "rows":[
                [
                    {
                        "components":[
                            {
                                "autofocus":false,
                                "input":true,
                                "tableView":true,
                                "label":"Select",
                                "key":"tableSelect",
                                "placeholder":"",
                                "data":{
                                    "values":[
                                        {
                                            "value":"1",
                                            "label":"1"
                                        },
                                        {
                                            "value":"2",
                                            "label":"2"
                                        },
                                        {
                                            "value":"3",
                                            "label":"3"
                                        },
                                        {
                                            "value":"4",
                                            "label":"4"
                                        }
                                    ],
                                    "json":"",
                                    "url":"",
                                    "resource":"",
                                    "custom":""
                                },
                                "dataSrc":"values",
                                "valueProperty":"",
                                "defaultValue":"",
                                "refreshOn":"",
                                "filter":"",
                                "authenticate":false,
                                "template":"<span>{{ item.label }}</span>",
                                "multiple":false,
                                "protected":false,
                                "unique":false,
                                "persistent":true,
                                "hidden":false,
                                "clearOnHide":true,
                                "validate":{
                                    "required":false
                                },
                                "type":"select",
                                "labelPosition":"top",
                                "tags":[

                                ],
                                "conditional":{
                                    "show":"",
                                    "when":null,
                                    "eq":""
                                },
                                "properties":{

                                }
                            }
                        ]
                    },
                    {
                        "components":[
                            {
                                "autofocus":false,
                                "input":true,
                                "tableView":true,
                                "label":"Select",
                                "key":"tableSelect2",
                                "placeholder":"",
                                "data":{
                                    "values":[
                                        {
                                            "value":"month",
                                            "label":"月"
                                        },
                                        {
                                            "value":"year",
                                            "label":"年"
                                        }
                                    ],
                                    "json":"",
                                    "url":"",
                                    "resource":"",
                                    "custom":""
                                },
                                "dataSrc":"values",
                                "valueProperty":"",
                                "defaultValue":"",
                                "refreshOn":"",
                                "filter":"",
                                "authenticate":false,
                                "template":"<span>{{ item.label }}</span>",
                                "multiple":false,
                                "protected":false,
                                "unique":false,
                                "persistent":true,
                                "hidden":false,
                                "clearOnHide":true,
                                "validate":{
                                    "required":false
                                },
                                "type":"select",
                                "labelPosition":"top",
                                "tags":[

                                ],
                                "conditional":{
                                    "show":"",
                                    "when":null,
                                    "eq":""
                                },
                                "properties":{

                                }
                            }
                        ]
                    }
                ]
            ],
            "header":[

            ],
            "caption":"",
            "striped":false,
            "bordered":false,
            "hover":false,
            "condensed":false,
            "tableView":false,
            "type":"table",
            "hideLabel":true,
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            }
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "label":"Select",
            "key":"select2",
            "placeholder":"",
            "data":{
                "values":[
                    {
                        "value":"1",
                        "label":"1"
                    },
                    {
                        "value":"2",
                        "label":"2"
                    },
                    {
                        "value":"3",
                        "label":"3"
                    },
                    {
                        "value":"5",
                        "label":"5"
                    },
                    {
                        "value":"7",
                        "label":"7"
                    }
                ],
                "json":"",
                "url":"",
                "resource":"",
                "custom":""
            },
            "dataSrc":"values",
            "valueProperty":"",
            "defaultValue":"",
            "refreshOn":"",
            "filter":"",
            "authenticate":false,
            "template":"<span>{{ item.label }}</span>",
            "multiple":false,
            "protected":false,
            "unique":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "validate":{
                "required":false
            },
            "type":"select",
            "labelPosition":"top",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            }
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "inputType":"text",
            "inputMask":"",
            "label":"Text",
            "key":"text",
            "placeholder":"Enter Name",
            "prefix":"",
            "suffix":"",
            "multiple":false,
            "defaultValue":"",
            "protected":false,
            "unique":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "spellcheck":true,
            "validate":{
                "required":true,
                "minLength":20,
                "maxLength":100,
                "pattern":"",
                "custom":"",
                "customPrivate":false,
                "customMessage":""
            },
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "type":"textfield",
            "labelPosition":"top",
            "inputFormat":"plain",
            "tags":[
                "zuixin",
                "haode"
            ],
            "properties":{
                "qw":"qw",
                "":""
            },
            "tabindex":"we",
            "lockKey":true,
            "labelWidth":30,
            "labelMargin":3
        },
        {
            "clearOnHide":false,
            "key":"panel",
            "input":false,
            "title":"user message",
            "theme":"default",
            "tableView":true,
            "components":[
                {
                    "autofocus":false,
                    "input":true,
                    "tableView":true,
                    "inputType":"text",
                    "inputMask":"",
                    "label":"City / Regency (ID)",
                    "key":"panelText",
                    "placeholder":"",
                    "prefix":"",
                    "suffix":"",
                    "multiple":false,
                    "defaultValue":"",
                    "protected":false,
                    "unique":false,
                    "persistent":true,
                    "hidden":false,
                    "clearOnHide":true,
                    "spellcheck":true,
                    "validate":{
                        "required":true,
                        "minLength":"",
                        "maxLength":"",
                        "pattern":"",
                        "custom":"",
                        "customPrivate":false
                    },
                    "conditional":{
                        "show":"",
                        "when":null,
                        "eq":""
                    },
                    "type":"textfield",
                    "labelPosition":"top",
                    "inputFormat":"plain",
                    "tags":[

                    ],
                    "properties":{

                    }
                },
                {
                    "autofocus":false,
                    "input":true,
                    "tableView":true,
                    "label":"Select",
                    "key":"panelSelect",
                    "placeholder":"",
                    "data":{
                        "values":[
                            {
                                "value":"1",
                                "label":"1"
                            },
                            {
                                "value":"2",
                                "label":"2"
                            },
                            {
                                "value":"3",
                                "label":"3"
                            }
                        ],
                        "json":"",
                        "url":"",
                        "resource":"",
                        "custom":""
                    },
                    "dataSrc":"values",
                    "valueProperty":"",
                    "defaultValue":"",
                    "refreshOn":"",
                    "filter":"",
                    "authenticate":false,
                    "template":"<span>{{ item.label }}</span>",
                    "multiple":false,
                    "protected":false,
                    "unique":false,
                    "persistent":true,
                    "hidden":false,
                    "clearOnHide":true,
                    "validate":{
                        "required":true
                    },
                    "type":"select",
                    "labelPosition":"top",
                    "tags":[

                    ],
                    "conditional":{
                        "show":"",
                        "when":null,
                        "eq":""
                    },
                    "properties":{

                    }
                },
                {
                    "autofocus":false,
                    "input":true,
                    "tableView":true,
                    "inputType":"number",
                    "label":"Number",
                    "key":"panelNumber",
                    "placeholder":"",
                    "prefix":"",
                    "suffix":"",
                    "defaultValue":"",
                    "protected":false,
                    "persistent":true,
                    "hidden":false,
                    "clearOnHide":true,
                    "validate":{
                        "required":false,
                        "min":"",
                        "max":"",
                        "step":"any",
                        "integer":"",
                        "multiple":"",
                        "custom":""
                    },
                    "type":"number",
                    "labelPosition":"top",
                    "tags":[

                    ],
                    "conditional":{
                        "show":"",
                        "when":null,
                        "eq":""
                    },
                    "properties":{

                    }
                }
            ],
            "type":"panel",
            "breadcrumb":"default",
            "hideLabel":false,
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            },
            "collapsible":false
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "label":"Address",
            "key":"address",
            "placeholder":"",
            "multiple":false,
            "protected":false,
            "clearOnHide":true,
            "unique":false,
            "persistent":true,
            "hidden":false,
            "map":{
                "region":"Dalls",
                "key":"AIzaSyA1KDMq35wgMnrZoCeuneptl9MSAqf31uo"
            },
            "validate":{
                "required":false
            },
            "type":"address",
            "labelPosition":"top",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            }
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "label":"Day",
            "key":"day2",
            "fields":{
                "day":{
                    "type":"number",
                    "placeholder":"",
                    "required":false,
                    "hide":true
                },
                "month":{
                    "type":"select",
                    "placeholder":"",
                    "required":false,
                    "hide":false
                },
                "year":{
                    "type":"number",
                    "placeholder":"",
                    "required":false,
                    "hide":true
                }
            },
            "dayFirst":false,
            "protected":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "validate":{
                "custom":""
            },
            "type":"day",
            "labelPosition":"top",
            "inputsLabelPosition":"top",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            }
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "inputType":"text",
            "inputMask":"",
            "label":"Currency",
            "key":"currency2",
            "placeholder":"",
            "prefix":"",
            "suffix":"",
            "defaultValue":"",
            "protected":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "delimiter":true,
            "decimalLimit":1,
            "requireDecimal":true,
            "validate":{
                "required":false,
                "multiple":"",
                "custom":""
            },
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "type":"currency",
            "labelPosition":"top",
            "tags":[

            ],
            "properties":{

            },
            "lockKey":true
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "inputType":"number",
            "label":"Number",
            "key":"number2",
            "placeholder":"",
            "prefix":"",
            "suffix":"",
            "defaultValue":"",
            "protected":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "validate":{
                "required":true,
                "min":1000,
                "max":1000000,
                "step":"any",
                "integer":"",
                "multiple":"",
                "custom":""
            },
            "type":"number",
            "labelPosition":"top",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            },
            "decimalLimit":-1
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "inputType":"number",
            "label":"Number",
            "key":"number",
            "placeholder":"Enter Number",
            "prefix":"",
            "suffix":"",
            "defaultValue":"",
            "protected":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "validate":{
                "required":false,
                "min":null,
                "max":null,
                "step":"any",
                "integer":"",
                "multiple":"",
                "custom":""
            },
            "type":"number",
            "labelPosition":"top",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            }
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "inputType":"text",
            "inputMask":"",
            "label":"Currency",
            "key":"currency",
            "placeholder":"Enter money",
            "prefix":"",
            "suffix":"",
            "defaultValue":"",
            "protected":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "delimiter":true,
            "decimalLimit":0,
            "requireDecimal":true,
            "validate":{
                "required":true,
                "multiple":"",
                "custom":""
            },
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "type":"currency",
            "labelPosition":"top",
            "tags":[

            ],
            "properties":{

            }
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "inputType":"time",
            "format":"HH:mm",
            "label":"Time",
            "key":"time",
            "placeholder":"",
            "prefix":"",
            "suffix":"",
            "defaultValue":"",
            "protected":false,
            "unique":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "type":"time",
            "labelPosition":"top",
            "inputFormat":"plain",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            }
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "label":"file",
            "key":"imgUrl",
            "image":true,
            "imageSize":"200",
            "placeholder":"",
            "multiple":true,
            "defaultValue":"",
            "protected":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "filePattern":"*",
            "fileMinSize":"0KB",
            "fileMaxSize":"1GB",
            "type":"file",
            "labelPosition":"top",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            },
            "hideLabel":true,
            "lockKey":true,
            "storage":"base64",
            "customClass":"photo-img"
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "label":"Date Time",
            "key":"dateTime",
            "placeholder":"",
            "format":"yyyy-MM-dd hh:mm a",
            "enableDate":true,
            "enableTime":true,
            "defaultDate":"",
            "datepickerMode":"day",
            "datePicker":{
                "showWeeks":true,
                "startingDay":0,
                "initDate":"",
                "minMode":"day",
                "maxMode":"year",
                "yearRows":4,
                "yearColumns":5,
                "minDate":null,
                "maxDate":null,
                "datepickerMode":"day"
            },
            "timePicker":{
                "hourStep":1,
                "minuteStep":1,
                "showMeridian":true,
                "readonlyInput":false,
                "mousewheel":true,
                "arrowkeys":true
            },
            "protected":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "validate":{
                "required":true,
                "custom":""
            },
            "type":"datetime",
            "labelPosition":"top",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            },
            "lockKey":true,
            "useLocaleSettings":false,
            "calculateServer":false
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "label":"Day",
            "key":"day",
            "fields":{
                "day":{
                    "type":"number",
                    "placeholder":"",
                    "required":true
                },
                "month":{
                    "type":"select",
                    "placeholder":"",
                    "required":true
                },
                "year":{
                    "type":"number",
                    "placeholder":"",
                    "required":true
                }
            },
            "dayFirst":false,
            "protected":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "validate":{
                "custom":""
            },
            "type":"day",
            "labelPosition":"top",
            "inputsLabelPosition":"top",
            "tags":[

            ],
            "conditional":{
                "show":"true",
                "when":null,
                "eq":""
            },
            "properties":{

            },
            "lockKey":true
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "label":"Select",
            "key":"select",
            "placeholder":"Enter List",
            "data":{
                "values":[
                    {
                        "value":"index",
                        "label":"index"
                    },
                    {
                        "value":"index1",
                        "label":"index1"
                    }
                ],
                "json":"",
                "url":"",
                "resource":"",
                "custom":""
            },
            "dataSrc":"values",
            "valueProperty":"",
            "defaultValue":"",
            "refreshOn":"",
            "filter":"",
            "authenticate":false,
            "template":"<span>{{ item.label }}</span>",
            "multiple":false,
            "protected":false,
            "unique":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "validate":{
                "required":true
            },
            "type":"select",
            "labelPosition":"top",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            }
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "inputType":"email",
            "label":"Email",
            "key":"email",
            "placeholder":"Enter Email",
            "prefix":"",
            "suffix":"",
            "defaultValue":"",
            "protected":false,
            "unique":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "kickbox":{
                "enabled":false
            },
            "type":"email",
            "labelPosition":"top",
            "inputFormat":"plain",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            },
            "spellcheck":true,
            "validate":{
                "minLength":10,
                "maxLength":100
            }
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "inputType":"text",
            "inputMask":"",
            "label":"Mobile Num",
            "key":"mobileNum",
            "placeholder":"Enter Mobile Num",
            "prefix":"",
            "suffix":"",
            "multiple":false,
            "defaultValue":"",
            "protected":false,
            "unique":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "spellcheck":true,
            "validate":{
                "required":false,
                "minLength":6,
                "maxLength":11,
                "pattern":"^[1][3,4,5,7,8][0-9]{9}$",
                "custom":"",
                "customPrivate":false
            },
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "type":"textfield",
            "labelPosition":"top",
            "inputFormat":"plain",
            "tags":[

            ],
            "properties":{

            }
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "label":"Text Area",
            "key":"textArea",
            "placeholder":"Enter Content",
            "prefix":"",
            "suffix":"",
            "rows":3,
            "multiple":false,
            "defaultValue":"",
            "protected":false,
            "persistent":true,
            "hidden":false,
            "wysiwyg":false,
            "clearOnHide":true,
            "spellcheck":true,
            "validate":{
                "required":false,
                "minLength":"",
                "maxLength":"",
                "pattern":"",
                "custom":""
            },
            "type":"textarea",
            "labelPosition":"top",
            "inputFormat":"plain",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            }
        },
        {
            "clearOnHide":false,
            "input":false,
            "key":"table2",
            "numRows":3,
            "numCols":3,
            "rows":[
                [
                    {
                        "components":[
                            {
                                "autofocus":false,
                                "input":true,
                                "tableView":true,
                                "inputType":"text",
                                "inputMask":"",
                                "label":"Text",
                                "key":"table2Text",
                                "placeholder":"",
                                "prefix":"",
                                "suffix":"",
                                "multiple":false,
                                "defaultValue":"",
                                "protected":false,
                                "unique":false,
                                "persistent":true,
                                "hidden":false,
                                "clearOnHide":true,
                                "spellcheck":true,
                                "validate":{
                                    "required":false,
                                    "minLength":"",
                                    "maxLength":"",
                                    "pattern":"",
                                    "custom":"",
                                    "customPrivate":false
                                },
                                "conditional":{
                                    "show":"",
                                    "when":null,
                                    "eq":""
                                },
                                "type":"textfield",
                                "labelPosition":"top",
                                "inputFormat":"plain",
                                "tags":[

                                ],
                                "properties":{

                                }
                            }
                        ]
                    },
                    {
                        "components":[
                            {
                                "autofocus":false,
                                "input":true,
                                "tableView":true,
                                "inputType":"text",
                                "inputMask":"",
                                "label":"Text",
                                "key":"table2Text2",
                                "placeholder":"",
                                "prefix":"",
                                "suffix":"",
                                "multiple":false,
                                "defaultValue":"",
                                "protected":false,
                                "unique":false,
                                "persistent":true,
                                "hidden":false,
                                "clearOnHide":true,
                                "spellcheck":true,
                                "validate":{
                                    "required":false,
                                    "minLength":"",
                                    "maxLength":"",
                                    "pattern":"",
                                    "custom":"",
                                    "customPrivate":false
                                },
                                "conditional":{
                                    "show":"",
                                    "when":null,
                                    "eq":""
                                },
                                "type":"textfield",
                                "labelPosition":"top",
                                "inputFormat":"plain",
                                "tags":[

                                ],
                                "properties":{

                                }
                            }
                        ]
                    },
                    {
                        "components":[
                            {
                                "autofocus":false,
                                "input":true,
                                "tableView":true,
                                "inputType":"text",
                                "inputMask":"",
                                "label":"Text",
                                "key":"table2Text3",
                                "placeholder":"",
                                "prefix":"",
                                "suffix":"",
                                "multiple":false,
                                "defaultValue":"",
                                "protected":false,
                                "unique":false,
                                "persistent":true,
                                "hidden":false,
                                "clearOnHide":true,
                                "spellcheck":true,
                                "validate":{
                                    "required":false,
                                    "minLength":"",
                                    "maxLength":"",
                                    "pattern":"",
                                    "custom":"",
                                    "customPrivate":false
                                },
                                "conditional":{
                                    "show":"",
                                    "when":null,
                                    "eq":""
                                },
                                "type":"textfield",
                                "labelPosition":"top",
                                "inputFormat":"plain",
                                "tags":[

                                ],
                                "properties":{

                                }
                            }
                        ]
                    }
                ],
                [
                    {
                        "components":[
                            {
                                "autofocus":false,
                                "input":true,
                                "tableView":true,
                                "inputType":"text",
                                "inputMask":"",
                                "label":"Text",
                                "key":"table2Text4",
                                "placeholder":"",
                                "prefix":"",
                                "suffix":"",
                                "multiple":false,
                                "defaultValue":"",
                                "protected":false,
                                "unique":false,
                                "persistent":true,
                                "hidden":false,
                                "clearOnHide":true,
                                "spellcheck":true,
                                "validate":{
                                    "required":false,
                                    "minLength":"",
                                    "maxLength":"",
                                    "pattern":"",
                                    "custom":"",
                                    "customPrivate":false
                                },
                                "conditional":{
                                    "show":"",
                                    "when":null,
                                    "eq":""
                                },
                                "type":"textfield",
                                "labelPosition":"top",
                                "inputFormat":"plain",
                                "tags":[

                                ],
                                "properties":{

                                }
                            }
                        ]
                    },
                    {
                        "components":[
                            {
                                "autofocus":false,
                                "input":true,
                                "tableView":true,
                                "inputType":"text",
                                "inputMask":"",
                                "label":"Text",
                                "key":"table2Text5",
                                "placeholder":"",
                                "prefix":"",
                                "suffix":"",
                                "multiple":false,
                                "defaultValue":"",
                                "protected":false,
                                "unique":false,
                                "persistent":true,
                                "hidden":false,
                                "clearOnHide":true,
                                "spellcheck":true,
                                "validate":{
                                    "required":false,
                                    "minLength":"",
                                    "maxLength":"",
                                    "pattern":"",
                                    "custom":"",
                                    "customPrivate":false
                                },
                                "conditional":{
                                    "show":"",
                                    "when":null,
                                    "eq":""
                                },
                                "type":"textfield",
                                "labelPosition":"top",
                                "inputFormat":"plain",
                                "tags":[

                                ],
                                "properties":{

                                }
                            }
                        ]
                    },
                    {
                        "components":[
                            {
                                "autofocus":false,
                                "input":true,
                                "tableView":true,
                                "inputType":"number",
                                "label":"Number",
                                "key":"table2Number",
                                "placeholder":"",
                                "prefix":"",
                                "suffix":"",
                                "defaultValue":"",
                                "protected":false,
                                "persistent":true,
                                "hidden":false,
                                "clearOnHide":true,
                                "validate":{
                                    "required":false,
                                    "min":"",
                                    "max":"",
                                    "step":"any",
                                    "integer":"",
                                    "multiple":"",
                                    "custom":""
                                },
                                "type":"number",
                                "labelPosition":"top",
                                "tags":[

                                ],
                                "conditional":{
                                    "show":"",
                                    "when":null,
                                    "eq":""
                                },
                                "properties":{

                                }
                            }
                        ]
                    }
                ],
                [
                    {
                        "components":[

                        ]
                    },
                    {
                        "components":[

                        ]
                    },
                    {
                        "components":[

                        ]
                    }
                ]
            ],
            "header":[

            ],
            "caption":"",
            "striped":false,
            "bordered":false,
            "hover":false,
            "condensed":false,
            "tableView":false,
            "type":"table",
            "hideLabel":true,
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            }
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":true,
            "label":"Select Boxes",
            "key":"selectBoxes",
            "values":[
                {
                    "value":"index",
                    "label":"index",
                    "shortcut":""
                },
                {
                    "value":"index2",
                    "label":"index2",
                    "shortcut":""
                },
                {
                    "value":"index3",
                    "label":"index3",
                    "shortcut":""
                },
                {
                    "value":"",
                    "label":"",
                    "shortcut":""
                }
            ],
            "inline":false,
            "protected":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "validate":{
                "required":false
            },
            "type":"selectboxes",
            "labelPosition":"top",
            "optionsLabelPosition":"right",
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            },
            "lockKey":true,
            "tabindex":"1"
        },
        {
            "autofocus":false,
            "input":true,
            "inputType":"checkbox",
            "tableView":false,
            "label":"fuxuankuang",
            "dataGridLabel":false,
            "key":"fuxuankuang",
            "defaultValue":"true",
            "protected":false,
            "persistent":false,
            "hidden":false,
            "name":"",
            "value":"",
            "clearOnHide":false,
            "validate":{
                "required":false
            },
            "type":"checkbox",
            "labelPosition":"right",
            "hideLabel":false,
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            }
        },
        {
            "autofocus":false,
            "input":true,
            "tableView":false,
            "inputType":"radio",
            "label":"Radio",
            "key":"radio",
            "values":[
                {
                    "value":"index",
                    "label":"index",
                    "shortcut":""
                },
                {
                    "value":"index2",
                    "label":"index2",
                    "shortcut":""
                }
            ],
            "defaultValue":"",
            "protected":false,
            "fieldSet":false,
            "persistent":false,
            "hidden":false,
            "clearOnHide":false,
            "validate":{
                "required":false,
                "custom":"",
                "customPrivate":false
            },
            "type":"radio",
            "labelPosition":"top",
            "optionsLabelPosition":"right",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            },
            "dataGridLabel":false
        },
        {
            "key":"tupian",
            "label":"tupian",
            "input":false,
            "tag":"img",
            "attrs":[
                {
                    "value":"https://img1.famulei.com/z/6259938/p/193/0313502781852.jpg?x-oss-process=image/resize,m_fixed,h_260,w_520,limit_0",
                    "attr":"src"
                }
            ],
            "className":"",
            "content":"image",
            "type":"htmlelement",
            "hideLabel":true,
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            }
        },
        {
            "key":"content",
            "input":false,
            "html":"<p>fdhdfhdfhfgh</p>\n",
            "type":"content",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            },
            "customClass":"user-list",
            "lockKey":true
        },
        {
            "input":true,
            "tableView":true,
            "label":"Signature",
            "key":"signature",
            "placeholder":"",
            "footer":"Sign above",
            "width":"100%",
            "height":"150px",
            "penColor":"black",
            "backgroundColor":"rgb(245,245,235)",
            "minWidth":"0.5",
            "maxWidth":"2.5",
            "protected":false,
            "persistent":true,
            "hidden":false,
            "clearOnHide":true,
            "validate":{
                "required":false
            },
            "type":"signature",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            },
            "hideLabel":true
        },
        {
            "autofocus":false,
            "input":true,
            "label":"Submit",
            "tableView":false,
            "key":"submit",
            "size":"md",
            "leftIcon":"",
            "rightIcon":"",
            "block":false,
            "action":"submit",
            "disableOnInvalid":false,
            "theme":"primary",
            "type":"button",
            "tags":[

            ],
            "conditional":{
                "show":"",
                "when":null,
                "eq":""
            },
            "properties":{

            }
        }
    ],
    "revisions":"",
    "_vid":0,
    "title":"yabei",
    "display":"form",
    "access":[
        {
            "roles":[

            ],
            "type":"create_own"
        },
        {
            "roles":[

            ],
            "type":"create_all"
        },
        {
            "roles":[

            ],
            "type":"read_own"
        },
        {
            "roles":[
                "5c65256c3666601dab919dd2",
                "5c65256c366660281c919dd3",
                "5c65256c366660d2eb919dd4"
            ],
            "type":"read_all"
        },
        {
            "roles":[

            ],
            "type":"update_own"
        },
        {
            "roles":[

            ],
            "type":"update_all"
        },
        {
            "roles":[

            ],
            "type":"delete_own"
        },
        {
            "roles":[

            ],
            "type":"delete_all"
        },
        {
            "roles":[

            ],
            "type":"team_read"
        },
        {
            "roles":[

            ],
            "type":"team_write"
        },
        {
            "roles":[

            ],
            "type":"team_admin"
        }
    ],
    "submissionAccess":[
        {
            "roles":[
                "5c65256c366660281c919dd3"
            ],
            "type":"create_own"
        },
        {
            "roles":[

            ],
            "type":"create_all"
        },
        {
            "roles":[

            ],
            "type":"read_own"
        },
        {
            "roles":[
                "5c65256c366660281c919dd3"
            ],
            "type":"read_all"
        },
        {
            "roles":[
                "5c65256c366660281c919dd3"
            ],
            "type":"update_own"
        },
        {
            "roles":[

            ],
            "type":"update_all"
        },
        {
            "roles":[

            ],
            "type":"delete_own"
        },
        {
            "roles":[
                "5c65256c366660281c919dd3"
            ],
            "type":"delete_all"
        },
        {
            "roles":[

            ],
            "type":"team_read"
        },
        {
            "roles":[

            ],
            "type":"team_write"
        },
        {
            "roles":[

            ],
            "type":"team_admin"
        }
    ],
    "settings":{

    },
    "path":"yabei",
    "name":"yabei",
    "project":"5c65256c3666600d6e919dd1",
    "created":"2019-02-24T07:22:08.063Z",
    "modified":"2019-06-24T00:58:35.759Z",
    "machineName":"soynopvqvkjpezo:yabei"
};

